services:

  db:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
      - ./data/seed:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    container_name: minio_server
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./data/minio_data:/data
    ports:
      - "9001:9001"
      - "9000:9000"
    command: server --console-address ":9001" /data 

  minio-create-bucket:
      image: minio/mc
      depends_on:
        - minio
      entrypoint: >
        /bin/sh -c "
        sleep 5;
        /usr/bin/mc alias set myminio http://minio:9000 admin admin123;
        /usr/bin/mc mb myminio/desafioseplag;
        /usr/bin/mc policy set public myminio/desafioseplag;
        exit 0;
        "

  app:
    build: ./app
    container_name: app-desafio-seplag
    depends_on:
      - db
      - minio
    restart: always
    ports:
      - "8083:8083"
